test:
  image: ubuntu
  script:
    - ls -alh
    - pwd
    - mkdir ~/.emacs.d
    - cp * ~/.emacs.d/
    - cd  ~/.emacs.d/
    - echo "now at"
    - pwd
    - apt-get -y update
    - apt-get -y install emacs
    - emacs -batch --eval="(message (number-to-string (+ 1 2)))"
    - emacs -batch -l ./init.el
