;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-sexp
	c-electric-pound
	comment-region
	cua--prefix-override-handler
	cua-paste
	forward-sexp
	org-ctrl-c-ctrl-c
	org-delete-char
	org-end-of-line
	org-self-insert-command
	transpose-words
	))

(setq mc/cmds-to-run-once
      '(
	helm-mini
	toggle-swift-mode
	yaml-electric-backspace
	))
