;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-sexp
	c-electric-pound
	c-electric-semi&comma
	comment-region
	cua-copy-handler
	cua-paste
	forward-sexp
	indent-for-tab-command
	org-delete-char
	))

(setq mc/cmds-to-run-once
      '(
	))
