(use-package tree-sitter :defer 4
  :hook (agda-mode       . (lambda () (tree-sitter-hl-mode)))
  :hook (sh-mode         . (lambda () (tree-sitter-hl-mode)))
  :hook (c-mode          . (lambda () (tree-sitter-hl-mode)))
  :hook (caml-mode       . (lambda () (tree-sitter-hl-mode)))
  :hook (csharp-mode     . (lambda () (tree-sitter-hl-mode)))
  :hook (c++-mode        . (lambda () (tree-sitter-hl-mode)))
  :hook (d-mode          . (lambda () (tree-sitter-hl-mode)))
  :hook (css-mode        . (lambda () (tree-sitter-hl-mode)))
  :hook (elm-mode        . (lambda () (tree-sitter-hl-mode)))
  :hook (elixir-mode     . (lambda () (tree-sitter-hl-mode)))
  :hook (go-mode         . (lambda () (tree-sitter-hl-mode)))
  :hook (hcl-mode        . (lambda () (tree-sitter-hl-mode)))
  :hook (terraform-mode  . (lambda () (tree-sitter-hl-mode)))
  :hook (html-mode       . (lambda () (tree-sitter-hl-mode)))
  :hook (mhtml-mode      . (lambda () (tree-sitter-hl-mode)))
  :hook (nix-mode        . (lambda () (tree-sitter-hl-mode)))
  :hook (java-mode       . (lambda () (tree-sitter-hl-mode)))
  :hook (javascript-mode . (lambda () (tree-sitter-hl-mode)))
  :hook (js-mode         . (lambda () (tree-sitter-hl-mode)))
  :hook (js2-mode        . (lambda () (tree-sitter-hl-mode)))
  :hook (js3-mode        . (lambda () (tree-sitter-hl-mode)))
  :hook (json-mode       . (lambda () (tree-sitter-hl-mode)))
  :hook (jsonc-mode      . (lambda () (tree-sitter-hl-mode)))
  :hook (julia-mode      . (lambda () (tree-sitter-hl-mode)))
  :hook (ocaml-mode      . (lambda () (tree-sitter-hl-mode)))
  :hook (php-mode        . (lambda () (tree-sitter-hl-mode)))
  :hook (prisma-mode     . (lambda () (tree-sitter-hl-mode)))
  :hook (python-mode     . (lambda () (tree-sitter-hl-mode)))
  :hook (pygn-mode       . (lambda () (tree-sitter-hl-mode)))
  :hook (rjsx-mode       . (lambda () (tree-sitter-hl-mode)))
  :hook (ruby-mode       . (lambda () (tree-sitter-hl-mode)))
  :hook (rust-mode       . (lambda () (tree-sitter-hl-mode)))
  :hook (rustic-mode     . (lambda () (tree-sitter-hl-mode)))
  :hook (scala-mode      . (lambda () (tree-sitter-hl-mode)))
  :hook (swift-mode      . (lambda () (tree-sitter-hl-mode)))
  :hook (tuareg-mode     . (lambda () (tree-sitter-hl-mode)))
  :hook (typescript-mode . (lambda () (tree-sitter-hl-mode)))
  :hook (zig-mode        . (lambda () (tree-sitter-hl-mode)))

  :diminish tree-sitter-hl-mode
  :diminish tree-sitter-debug-mode)

(use-package tree-sitter-langs)
