;;; yasnippet-classic-snippets-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from yasnippet-classic-snippets.el

 (eval-after-load 'yasnippet '(require 'yasnippet-classic-snippets))
(register-definition-prefixes "yasnippet-classic-snippets" '("yasnippet-classic-snippets-dir"))

;;; End of scraped data

(provide 'yasnippet-classic-snippets-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; yasnippet-classic-snippets-autoloads.el ends here
